SharedData = {}

SharedData.Weapons = {
	{
		Name        = 'Lasso',
		Desc        = '',
		AttachPoint = '',       --TODO add attach point
		HashName    = 'WEAPON_LASSO', -- DONT TOUCH
	},
	{
		Name        = 'Lasso Reforçado',
		Desc        = '',
		AttachPoint = '',
		HashName    = 'WEAPON_LASSO_REINFORCED',
	},
	{
		Name = 'Faca',
		Desc = '',
		AttachPoint = '',
		HashName = 'WEAPON_MELEE_KNIFE',
	},
	{
		Name = 'Faca Rústica',
		Desc = '',
		AttachPoint = '',
		HashName = 'WEAPON_MELEE_KNIFE_RUSTIC',
	},
	{
		Name = 'Knife Horror',
		Desc = '',
		AttachPoint = '',
		HashName = 'WEAPON_MELEE_KNIFE_HORROR',
	},
	{
		Name = 'Knife Civil War',
		Desc = '',
		AttachPoint = '',
		HashName = 'WEAPON_MELEE_KNIFE_CIVIL_WAR',
	},
	{
		Name = 'Knife Jawbone',
		Desc = '',
		AttachPoint = '',
		HashName = 'WEAPON_MELEE_KNIFE_JAWBONE',
	},
	{
		Name = 'Knife Miner',
		Desc = '',
		AttachPoint = '',
		HashName = 'WEAPON_MELEE_KNIFE_MINER',
	},
	{
		Name = 'Knife Vampire',
		Desc = '',
		AttachPoint = '',
		HashName = 'WEAPON_MELEE_KNIFE_VAMPIRE',
	},
	{
		Name = 'Cleaver',
		Desc = '',
		AttachPoint = '',
		HashName = 'WEAPON_MELEE_CLEAVER',
	},
	{
		Name = 'Hachet',
		Desc = '',
		AttachPoint = '',
		HashName = 'WEAPON_MELEE_HATCHET',
	},
	{
		Name = 'Hachet Double Bit',
		Desc = '',
		AttachPoint = '',
		HashName = 'WEAPON_MELEE_HATCHET_DOUBLE_BIT',
	},
	{
		Name = 'Hachet Hewing',
		Desc = '',
		AttachPoint = '',
		HashName = 'WEAPON_MELEE_HATCHET_HEWING',
	},
	{
		Name = 'Hachet Hunter',
		Desc = '',
		AttachPoint = '',
		HashName = 'WEAPON_MELEE_HATCHET_HUNTER',
	},
	{
		Name = 'Hachet Viking',
		Desc = '',
		AttachPoint = '',
		HashName = 'WEAPON_MELEE_HATCHET_VIKING',
	},
	{
		Name = 'Tomahawk',
		Desc = '',
		AttachPoint = '',
		HashName = 'WEAPON_THROWN_TOMAHAWK',
	},
	{
		Name = 'Tomahawk Ancient',
		Desc = '',
		AttachPoint = '',
		HashName = 'WEAPON_THROWN_TOMAHAWK_ANCIENT',
	},
	{
		Name = 'Faca de Arremesso',
		Desc = '',
		AttachPoint = '',
		HashName = 'WEAPON_THROWN_THROWING_KNIVES',
	},
	{
		Name = 'Machete',
		Desc = '',
		AttachPoint = '',
		HashName = 'WEAPON_MELEE_MACHETE',
	},
	{
		Name = 'Arco',
		Desc = '',
		AttachPoint = '',
		HashName = 'WEAPON_BOW',
	},
	{
		Name = 'Pistola Semi-Auto',
		Desc = '',
		AttachPoint = '',
		HashName = 'WEAPON_PISTOL_SEMIAUTO',
	},
	{
		Name = 'Pistola Mauser',
		Desc = '',
		AttachPoint = '',
		HashName = 'WEAPON_PISTOL_MAUSER',
	},
	{
		Name = 'Pistola Volcanic',
		Desc = '',
		AttachPoint = '',
		HashName = 'WEAPON_PISTOL_VOLCANIC',
	},
	{
		Name = 'Pistola M1899',
		Desc = '',
		AttachPoint = '',
		HashName = 'WEAPON_PISTOL_M1899',
	},
	{
		Name = 'Revolver Schofield',
		Desc = '',
		AttachPoint = '',
		HashName = 'WEAPON_REVOLVER_SCHOFIELD',
	},
	{
		Name = 'Revolver Navy',
		Desc = '',
		AttachPoint = '',
		HashName = 'WEAPON_REVOLVER_NAVY',
	},
	{
		Name = 'Revolver Navy Crossover',
		Desc = '',
		AttachPoint = '',
		HashName = 'WEAPON_REVOLVER_NAVY_CROSSOVER',
	},
	{
		Name = 'Revolver Lemat',
		Desc = '',
		AttachPoint = '',
		HashName = 'WEAPON_REVOLVER_LEMAT',
	},
	{
		Name = 'Revolver Dupla Ação',
		Desc = '',
		AttachPoint = '',
		HashName = 'WEAPON_REVOLVER_DOUBLEACTION',
	},
	{
		Name = 'Revolver Vaqueiro',
		Desc = '',
		AttachPoint = '',
		HashName = 'WEAPON_REVOLVER_CATTLEMAN',
	},
	{
		Name = 'Revolver Cattleman mexican',
		Desc = '',
		AttachPoint = '',
		HashName = 'WEAPON_REVOLVER_CATTLEMAN_MEXICAN',
	},
	{
		Name = 'Rifle Anti-Pragas',
		Desc = '',
		AttachPoint = '',
		HashName = 'WEAPON_RIFLE_VARMINT',
	},
	{
		Name = 'Carabina Winchester',
		Desc = '',
		AttachPoint = '',
		HashName = 'WEAPON_REPEATER_WINCHESTER',
	},
	{
		Name = 'Carabina Henry',
		Desc = '',
		AttachPoint = '',
		HashName = 'WEAPON_REPEATER_HENRY',
	},
	{
		Name = 'Carabina Evans',
		Desc = '',
		AttachPoint = '',
		HashName = 'WEAPON_REPEATER_EVANS',
	},
	{
		Name = 'Carabina de Repetição',
		Desc = '',
		AttachPoint = '',
		HashName = 'WEAPON_REPEATER_CARBINE',
	},
	{
		Name = 'Rifle Rolling Block',
		Desc = '',
		AttachPoint = '',
		HashName = 'WEAPON_SNIPERRIFLE_ROLLINGBLOCK',
	},
	{
		Name = 'Rifle Carcano',
		Desc = '',
		AttachPoint = '',
		HashName = 'WEAPON_SNIPERRIFLE_CARCANO',
	},
	{
		Name = 'Rifle Springfield',
		Desc = '',
		AttachPoint = '',
		HashName = 'WEAPON_RIFLE_SPRINGFIELD',
	},
	{
		Name = 'Rifle Elephant',
		Desc = '',
		AttachPoint = '',
		HashName = 'WEAPON_RIFLE_ELEPHANT',
	},
	{
		Name = 'Rifle Ferrolho',
		Desc = '',
		AttachPoint = '',
		HashName = 'WEAPON_RIFLE_BOLTACTION',
	},
	{
		Name = 'Escopeta Semi-Auto',
		Desc = '',
		AttachPoint = '',
		HashName = 'WEAPON_SHOTGUN_SEMIAUTO',
	},
	{
		Name = 'Escopeta Sawedoff',
		Desc = '',
		AttachPoint = '',
		HashName = 'WEAPON_SHOTGUN_SAWEDOFF',
	},
	{
		Name = 'Escopeta Repetidora',
		Desc = '',
		AttachPoint = '',
		HashName = 'WEAPON_SHOTGUN_REPEATING',
	},
	{
		Name = 'Escopeta Duplo Cano Exótica',
		Desc = '',
		AttachPoint = '',
		HashName = 'WEAPON_SHOTGUN_DOUBLEBARREL_EXOTIC',
	},
	{
		Name = 'Escopeta Punheteira',
		Desc = '',
		AttachPoint = '',
		HashName = 'WEAPON_SHOTGUN_PUMP',
	},
	{
		Name = 'Escopeta Duplo Cano',
		Desc = '',
		AttachPoint = '',
		HashName = 'WEAPON_SHOTGUN_DOUBLEBARREL',
	},
	{
		Name = 'Camera',
		Desc = '',
		AttachPoint = '',
		HashName = 'WEAPON_KIT_CAMERA',
	},
	{
		Name = 'Improved Binoculars',
		Desc = '',
		AttachPoint = '',
		HashName = 'WEAPON_KIT_BINOCULARS_IMPROVED',
	},
	{
		Name = 'Knife Trader',
		Desc = '',
		AttachPoint = '',
		HashName = 'WEAPON_MELEE_KNIFE_TRADER',
	},
	{
		Name = 'Binoculars',
		Desc = '',
		AttachPoint = '',
		HashName = 'WEAPON_KIT_BINOCULARS',
	},
	{
		Name = 'Advanced Camera',
		Desc = '',
		AttachPoint = '',
		HashName = 'WEAPON_KIT_CAMERA_ADVANCED',
	},
	{
		Name = 'Lampião',
		Desc = '',
		AttachPoint = '',
		HashName = 'WEAPON_MELEE_LANTERN',
	},
	{
		Name = 'Davy Lantern',
		Desc = '',
		AttachPoint = '',
		HashName = 'WEAPON_MELEE_DAVY_LANTERN',
	},
	{
		Name = 'Halloween Lantern',
		Desc = '',
		AttachPoint = '',
		HashName = 'WEAPON_MELEE_LANTERN_HALLOWEEN',
	},
	{
		Name = 'Poison Bottle',
		Desc = '',
		AttachPoint = '',
		HashName = 'WEAPON_THROWN_POISONBOTTLE',
	},
	{
		Name = 'Metal Detector',
		Desc = '',
		AttachPoint = '',
		HashName = 'WEAPON_KIT_METAL_DETECTOR',
	},
	{
		Name = 'Dinamite',
		Desc = '',
		AttachPoint = '',
		HashName = 'WEAPON_THROWN_DYNAMITE',
	},
	{
		Name = 'Molotov',
		Desc = '',
		AttachPoint = '',
		HashName = 'WEAPON_THROWN_MOLOTOV',
	},
	{
		Name = 'Improved Bow',
		Desc = '',
		AttachPoint = '',
		HashName = 'WEAPON_BOW_IMPROVED',
	},
	{
		Name = 'Machete Collector',
		Desc = '',
		AttachPoint = '',
		HashName = 'WEAPON_MELEE_MACHETE_COLLECTOR',
	},
	{
		Name = 'Electric Lantern',
		Desc = '',
		AttachPoint = '',
		HashName = 'WEAPON_MELEE_LANTERN_ELECTRIC',
	},
	{
		Name = 'Torch',
		Desc = '',
		AttachPoint = '',
		HashName = 'WEAPON_MELEE_TORCH',
	},
	{
		Name = 'Moonshine Jug',
		Desc = '',
		AttachPoint = '',
		HashName = 'WEAPON_MOONSHINEJUG_MP',
	},
	{
		Name = 'Bolas',
		Desc = '',
		AttachPoint = '',
		HashName = 'WEAPON_THROWN_BOLAS',
	},
	{
		Name = 'Bolas Hawkmoth',
		Desc = '',
		AttachPoint = '',
		HashName = 'WEAPON_THROWN_BOLAS_HAWKMOTH',
	},
	{
		Name = 'Bolas Ironspiked',
		Desc = '',
		AttachPoint = '',
		HashName = 'WEAPON_THROWN_BOLAS_IRONSPIKED',
	},
	{
		Name = 'Bolas Intertwined',
		Desc = '',
		AttachPoint = '',
		HashName = 'WEAPON_THROWN_BOLAS_INTERTWINED',
	},
	{
		Name = 'Fishing Rod',
		Desc = '',
		AttachPoint = '',
		HashName = 'WEAPON_FISHINGROD',
	},
	{
		Name = 'Machete Horror',
		Desc = '',
		AttachPoint = '',
		HashName = 'WEAPON_MACHETE_HORROR',
	},
	{
		Name = 'Lantern Haloween',
		Desc = '',
		AttachPoint = '',
		HashName = 'WEAPON_MELEE_LANTERN_HALOWEEN',
	},
	{
		Name = 'Hammer',
		Desc = '',
		AttachPoint = '',
		HashName = 'WEAPON_MELEE_HAMMER',
	},
}
